#! /usr/bin/python

import os, sys, re

def mkhtml(fname):
    with open(fname, 'r') as f:
        txt = f.read()
    with open(fname, 'w') as f:
        f.write('<html><body>\n' + txt.strip() + '\n</body></html>')
    os.rename(fname, fname.replace('.txt', '.html'))

if __name__ == '__main__':
    for fname in sys.argv[1:]:
        mkhtml(fname)