#! /usr/bin/python

import os, sys, re

open_curly_quote = '\xe2\x80\x9c'
ellipsis = '\xe2\x80\xa6'
close_curly_quote = '\xe2\x80\x9d'

def unquote(fname):
    with open(fname, 'r') as f:
        txt = f.read()
    txt = txt.replace(ellipsis, '...')
    txt = txt.replace(open_curly_quote, '"')
    txt = txt.replace(close_curly_quote, '"')
    
    i = 0
    while True:
        i = txt.find('"', i)
        if i == -1:
            break
        j = txt.find('"', i + 1)
        if j == -1:
            print('Unbalanced quotes for %s.' % fname)
            break
        txt = txt[:i] + '"..."' + txt[j + 1:]
        i += 5
    with open(fname, 'w') as f:
        f.write(txt)

if __name__ == '__main__':
    for fname in sys.argv[1:]:
        unquote(fname)